language: java

matrix:
    - jdk: oraclejdk8
      env: _MVN_GOAL=goal1
    - jdk: oraclejdk7
      env: _MVN_GOAL=goal2

install: true

script:
    - export IS_RELEASE=`git log -1 --pretty=%s | grep "\[maven-release-plugin\] prepare release"`
    - echo "$IS_RELEASE"
    -
        if [ -z "$TRAVIS_TAG" -a -z "$IS_RELEASE" ]; then
            if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
                $_MVN clean install;
            else
                $_MVN clean verify;
            fi
        fi

env:
    global:
        - _MVN='mvn -B -V -e'
